/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mortalkombatbversion;
import org.apache.commons.beanutils.BeanUtils;
import mortalkombatbversion.Characters.Character;
import mortalkombatbversion.Characters.Player;
import org.modelmapper.ModelMapper;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Мария
 */
public class JFrames extends javax.swing.JFrame {
    
    Game game = new Game();
    Player player = null;
    Character enemy = null;
    Items[] items = new Items[3];
    String nameButton = "";

    
    /**
     * Creates new form JFrame
     */
    public JFrames() {
        initComponents();

        try {
            game.ReadFromExcel();
        } catch (IOException ex) {
            Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
        }
        game.WriteToTable(recordTable);
        
        itemBagBurronGroup.add(smallPotionRadio);
        itemBagBurronGroup.add(bigPotionRadio);
        itemBagBurronGroup.add(ressurectionCrossRadio);
        
        items[0]=new Items("Малое зелье лечение",0);
        items[1]=new Items("Большое зелье лечение",0);
        items[2]=new Items("Крест возрождения",0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fightFrame = new javax.swing.JFrame();
        FightPanel = new javax.swing.JPanel();
        playerIconLabel = new javax.swing.JLabel();
        atackButton = new javax.swing.JButton();
        defendButton = new javax.swing.JButton();
        playerHealthBar = new javax.swing.JProgressBar();
        enemyIconLabel = new javax.swing.JLabel();
        enemyHealthBar = new javax.swing.JProgressBar();
        enemyNameLAbel = new javax.swing.JLabel();
        damage1Label = new javax.swing.JLabel();
        damage2Label = new javax.swing.JLabel();
        playerDamageLabel = new javax.swing.JLabel();
        enemyDamageLabel = new javax.swing.JLabel();
        playerLevelLabel = new javax.swing.JLabel();
        fightLabel = new javax.swing.JLabel();
        playerHealthLabel = new javax.swing.JLabel();
        enemyHealthLabel = new javax.swing.JLabel();
        experienceLabel = new javax.swing.JLabel();
        pointLabel = new javax.swing.JLabel();
        experienceValueLabel = new javax.swing.JLabel();
        pointsValueLabel = new javax.swing.JLabel();
        enemyLevelLabel = new javax.swing.JLabel();
        turnLabel = new javax.swing.JLabel();
        lastActionLabel = new javax.swing.JLabel();
        playerNameLabel = new javax.swing.JLabel();
        effectLabel = new javax.swing.JLabel();
        itemsButton = new javax.swing.JButton();
        youWinDialog = new javax.swing.JDialog();
        youWinPanel = new javax.swing.JPanel();
        youWinLabel = new javax.swing.JLabel();
        youWinContinueButton = new javax.swing.JButton();
        recordWinDialog = new javax.swing.JDialog();
        recordWinPanel = new javax.swing.JPanel();
        recordWinLabel = new javax.swing.JLabel();
        recordWinNameField = new javax.swing.JTextField();
        recordWinLabel1 = new javax.swing.JLabel();
        recordWinLabel2 = new javax.swing.JLabel();
        recordWinEndButton = new javax.swing.JButton();
        recordTableDialog = new javax.swing.JDialog();
        recordTablePanel = new javax.swing.JPanel();
        recorTableLabel = new javax.swing.JLabel();
        recordTableScroll = new javax.swing.JScrollPane();
        recordTable = new javax.swing.JTable();
        closeRecordTableButton = new javax.swing.JButton();
        nonRecordWinDialog = new javax.swing.JDialog();
        nonRecordWinPanel = new javax.swing.JPanel();
        nonRecordWinLabel1 = new javax.swing.JLabel();
        nonRecordWinLabel2 = new javax.swing.JLabel();
        nonRecordEndButton = new javax.swing.JButton();
        bagOfItemsDialog = new javax.swing.JDialog();
        bagOfItemesPanel = new javax.swing.JPanel();
        bagOfItemsLabel = new javax.swing.JLabel();
        smallPotionRadio = new javax.swing.JRadioButton();
        bigPotionRadio = new javax.swing.JRadioButton();
        ressurectionCrossRadio = new javax.swing.JRadioButton();
        useItemButton = new javax.swing.JButton();
        itemBagBurronGroup = new javax.swing.ButtonGroup();
        cannotUseDialog = new javax.swing.JDialog();
        cannotUsePanel = new javax.swing.JPanel();
        uCannotUseLabel = new javax.swing.JLabel();
        thisItemLabel = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        mainMenuPanel = new javax.swing.JPanel();
        mortalKombatLabel = new javax.swing.JLabel();
        startNewGameButton = new javax.swing.JButton();
        showResultTableButton = new javax.swing.JButton();

        FightPanel.setBackground(new java.awt.Color(255, 255, 255));

        atackButton.setBackground(new java.awt.Color(255, 0, 0));
        atackButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        atackButton.setForeground(new java.awt.Color(0, 0, 0));
        atackButton.setText("Атаковать");
        atackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atackButtonActionPerformed(evt);
            }
        });

        defendButton.setBackground(new java.awt.Color(255, 204, 0));
        defendButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        defendButton.setForeground(new java.awt.Color(0, 0, 0));
        defendButton.setText("Защититься");
        defendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defendButtonActionPerformed(evt);
            }
        });

        playerHealthBar.setBackground(new java.awt.Color(204, 204, 204));
        playerHealthBar.setForeground(new java.awt.Color(51, 255, 51));
        playerHealthBar.setMaximum(80);
        playerHealthBar.setMinimum(-1);

        enemyHealthBar.setBackground(new java.awt.Color(204, 204, 204));
        enemyHealthBar.setForeground(new java.awt.Color(0, 255, 0));
        enemyHealthBar.setMinimum(-1);

        enemyNameLAbel.setBackground(new java.awt.Color(0, 0, 0));
        enemyNameLAbel.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N

        damage1Label.setBackground(new java.awt.Color(255, 255, 255));
        damage1Label.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        damage1Label.setForeground(new java.awt.Color(0, 0, 0));
        damage1Label.setText("Damage");

        damage2Label.setBackground(new java.awt.Color(255, 255, 255));
        damage2Label.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        damage2Label.setForeground(new java.awt.Color(0, 0, 0));
        damage2Label.setText("Damage");

        playerDamageLabel.setBackground(new java.awt.Color(255, 255, 255));
        playerDamageLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        playerDamageLabel.setForeground(new java.awt.Color(255, 0, 0));
        playerDamageLabel.setText("16");

        enemyDamageLabel.setBackground(new java.awt.Color(255, 255, 255));
        enemyDamageLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        enemyDamageLabel.setForeground(new java.awt.Color(255, 0, 0));
        enemyDamageLabel.setText("16");

        playerLevelLabel.setBackground(new java.awt.Color(255, 255, 255));
        playerLevelLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        playerLevelLabel.setForeground(new java.awt.Color(0, 0, 0));
        playerLevelLabel.setText("0 уровень");

        fightLabel.setBackground(new java.awt.Color(255, 255, 255));
        fightLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        fightLabel.setForeground(new java.awt.Color(0, 0, 153));
        fightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fightLabel.setText("FIGHT");
        fightLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        playerHealthLabel.setBackground(new java.awt.Color(255, 255, 255));
        playerHealthLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        playerHealthLabel.setForeground(new java.awt.Color(102, 102, 102));
        playerHealthLabel.setText("80/80");

        enemyHealthLabel.setBackground(new java.awt.Color(255, 255, 255));
        enemyHealthLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        enemyHealthLabel.setForeground(new java.awt.Color(102, 102, 102));
        enemyHealthLabel.setText("80/80");

        experienceLabel.setBackground(new java.awt.Color(255, 255, 255));
        experienceLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        experienceLabel.setForeground(new java.awt.Color(128, 92, 31));
        experienceLabel.setText("experience");

        pointLabel.setBackground(new java.awt.Color(255, 255, 255));
        pointLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        pointLabel.setForeground(new java.awt.Color(128, 92, 31));
        pointLabel.setText("points");

        experienceValueLabel.setBackground(new java.awt.Color(255, 255, 255));
        experienceValueLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        experienceValueLabel.setForeground(new java.awt.Color(113, 90, 16));
        experienceValueLabel.setText("0/40");

        pointsValueLabel.setBackground(new java.awt.Color(255, 255, 255));
        pointsValueLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pointsValueLabel.setForeground(new java.awt.Color(113, 90, 16));
        pointsValueLabel.setText("00");

        enemyLevelLabel.setBackground(new java.awt.Color(255, 255, 255));
        enemyLevelLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        enemyLevelLabel.setForeground(new java.awt.Color(0, 0, 0));
        enemyLevelLabel.setText("1 уровень");

        turnLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        turnLabel.setForeground(new java.awt.Color(0, 0, 0));
        turnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lastActionLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lastActionLabel.setForeground(new java.awt.Color(204, 0, 0));
        lastActionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        playerNameLabel.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        playerNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerNameLabel.setText("Kitana ");

        effectLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        effectLabel.setForeground(new java.awt.Color(0, 0, 0));
        effectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        itemsButton.setBackground(new java.awt.Color(174, 183, 106));
        itemsButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        itemsButton.setForeground(new java.awt.Color(0, 0, 0));
        itemsButton.setText("Предметы");
        itemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FightPanelLayout = new javax.swing.GroupLayout(FightPanel);
        FightPanel.setLayout(FightPanelLayout);
        FightPanelLayout.setHorizontalGroup(
            FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FightPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(enemyHealthLabel)
                .addGap(18, 18, 18)
                .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FightPanelLayout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(experienceLabel))
                        .addContainerGap())
                    .addGroup(FightPanelLayout.createSequentialGroup()
                        .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FightPanelLayout.createSequentialGroup()
                                .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FightPanelLayout.createSequentialGroup()
                                        .addComponent(enemyHealthBar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(FightPanelLayout.createSequentialGroup()
                                                .addGap(92, 92, 92)
                                                .addComponent(pointLabel))
                                            .addGroup(FightPanelLayout.createSequentialGroup()
                                                .addGap(111, 111, 111)
                                                .addComponent(pointsValueLabel)
                                                .addGap(108, 108, 108)
                                                .addComponent(experienceValueLabel))))
                                    .addGroup(FightPanelLayout.createSequentialGroup()
                                        .addComponent(damage1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(enemyDamageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(FightPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(enemyNameLAbel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE))
                            .addGroup(FightPanelLayout.createSequentialGroup()
                                .addComponent(enemyIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FightPanelLayout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(turnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(FightPanelLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lastActionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(effectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FightPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(itemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)))
                        .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FightPanelLayout.createSequentialGroup()
                                .addComponent(playerLevelLabel)
                                .addGap(26, 26, 26))
                            .addGroup(FightPanelLayout.createSequentialGroup()
                                .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FightPanelLayout.createSequentialGroup()
                                        .addComponent(playerHealthBar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(playerHealthLabel))
                                    .addGroup(FightPanelLayout.createSequentialGroup()
                                        .addComponent(damage2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(playerDamageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45))
                            .addGroup(FightPanelLayout.createSequentialGroup()
                                .addComponent(playerIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(FightPanelLayout.createSequentialGroup()
                                .addComponent(playerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))
                            .addGroup(FightPanelLayout.createSequentialGroup()
                                .addComponent(atackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(defendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))))))
            .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FightPanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(enemyLevelLabel)
                    .addContainerGap(854, Short.MAX_VALUE)))
        );
        FightPanelLayout.setVerticalGroup(
            FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FightPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(fightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(FightPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(playerHealthBar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(enemyHealthBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(FightPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(playerHealthLabel))
                            .addComponent(enemyHealthLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(FightPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(experienceLabel)
                            .addComponent(pointLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(experienceValueLabel)
                            .addComponent(pointsValueLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(damage2Label)
                    .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(damage1Label)
                        .addComponent(enemyDamageLabel)
                        .addComponent(playerDamageLabel)))
                .addGap(27, 27, 27)
                .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FightPanelLayout.createSequentialGroup()
                        .addComponent(enemyIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(enemyNameLAbel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(FightPanelLayout.createSequentialGroup()
                        .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(FightPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(playerLevelLabel)
                                .addGap(7, 7, 7)
                                .addComponent(playerIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FightPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lastActionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(turnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(effectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(playerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(itemsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(atackButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(defendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                        .addGap(14, 14, 14))))
            .addGroup(FightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FightPanelLayout.createSequentialGroup()
                    .addGap(229, 229, 229)
                    .addComponent(enemyLevelLabel)
                    .addContainerGap(380, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout fightFrameLayout = new javax.swing.GroupLayout(fightFrame.getContentPane());
        fightFrame.getContentPane().setLayout(fightFrameLayout);
        fightFrameLayout.setHorizontalGroup(
            fightFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fightFrameLayout.createSequentialGroup()
                .addComponent(FightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fightFrameLayout.setVerticalGroup(
            fightFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        youWinPanel.setBackground(new java.awt.Color(179, 226, 217));

        youWinLabel.setBackground(new java.awt.Color(204, 204, 204));
        youWinLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 42)); // NOI18N
        youWinLabel.setForeground(new java.awt.Color(204, 0, 0));
        youWinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        youWinLabel.setText("YOU WIN");
        youWinLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        youWinContinueButton.setBackground(new java.awt.Color(114, 218, 142));
        youWinContinueButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        youWinContinueButton.setForeground(new java.awt.Color(0, 0, 0));
        youWinContinueButton.setText("Дальше");
        youWinContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                youWinContinueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout youWinPanelLayout = new javax.swing.GroupLayout(youWinPanel);
        youWinPanel.setLayout(youWinPanelLayout);
        youWinPanelLayout.setHorizontalGroup(
            youWinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(youWinPanelLayout.createSequentialGroup()
                .addGroup(youWinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(youWinPanelLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(youWinContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(youWinPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(youWinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        youWinPanelLayout.setVerticalGroup(
            youWinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(youWinPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(youWinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(youWinContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout youWinDialogLayout = new javax.swing.GroupLayout(youWinDialog.getContentPane());
        youWinDialog.getContentPane().setLayout(youWinDialogLayout);
        youWinDialogLayout.setHorizontalGroup(
            youWinDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(youWinDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(youWinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        youWinDialogLayout.setVerticalGroup(
            youWinDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(youWinDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(youWinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        recordWinPanel.setBackground(new java.awt.Color(255, 204, 255));

        recordWinLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        recordWinLabel.setForeground(new java.awt.Color(255, 0, 0));
        recordWinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recordWinLabel.setText("Победа на вашей стороне");

        recordWinNameField.setBackground(new java.awt.Color(255, 255, 255));
        recordWinNameField.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        recordWinNameField.setForeground(new java.awt.Color(0, 0, 0));
        recordWinNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        recordWinNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordWinNameFieldActionPerformed(evt);
            }
        });

        recordWinLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        recordWinLabel1.setForeground(new java.awt.Color(102, 102, 102));
        recordWinLabel1.setText("Введите имя своего персонажа для добавления");

        recordWinLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        recordWinLabel2.setForeground(new java.awt.Color(102, 102, 102));
        recordWinLabel2.setText("результата в таблицу рекордов");

        recordWinEndButton.setBackground(new java.awt.Color(153, 153, 255));
        recordWinEndButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        recordWinEndButton.setForeground(new java.awt.Color(51, 51, 51));
        recordWinEndButton.setText("Закончить игру");
        recordWinEndButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordWinEndButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recordWinPanelLayout = new javax.swing.GroupLayout(recordWinPanel);
        recordWinPanel.setLayout(recordWinPanelLayout);
        recordWinPanelLayout.setHorizontalGroup(
            recordWinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recordWinPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(recordWinEndButton)
                .addGap(14, 14, 14))
            .addGroup(recordWinPanelLayout.createSequentialGroup()
                .addGroup(recordWinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recordWinPanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(recordWinLabel2))
                    .addGroup(recordWinPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(recordWinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(recordWinPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(recordWinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recordWinNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recordWinLabel1))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        recordWinPanelLayout.setVerticalGroup(
            recordWinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordWinPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(recordWinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recordWinLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recordWinLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(recordWinNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recordWinEndButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout recordWinDialogLayout = new javax.swing.GroupLayout(recordWinDialog.getContentPane());
        recordWinDialog.getContentPane().setLayout(recordWinDialogLayout);
        recordWinDialogLayout.setHorizontalGroup(
            recordWinDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordWinDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recordWinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        recordWinDialogLayout.setVerticalGroup(
            recordWinDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordWinDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recordWinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        recordTablePanel.setBackground(new java.awt.Color(204, 204, 255));

        recorTableLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        recorTableLabel.setForeground(new java.awt.Color(51, 51, 51));
        recorTableLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recorTableLabel.setText("Таблица рекордов");

        recordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Имя", "Количество баллов"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        recordTableScroll.setViewportView(recordTable);

        closeRecordTableButton.setBackground(new java.awt.Color(255, 255, 153));
        closeRecordTableButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        closeRecordTableButton.setForeground(new java.awt.Color(51, 51, 51));
        closeRecordTableButton.setText("Закрыть");
        closeRecordTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeRecordTableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recordTablePanelLayout = new javax.swing.GroupLayout(recordTablePanel);
        recordTablePanel.setLayout(recordTablePanelLayout);
        recordTablePanelLayout.setHorizontalGroup(
            recordTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordTablePanelLayout.createSequentialGroup()
                .addGroup(recordTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closeRecordTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(recordTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(recordTablePanelLayout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(recorTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(recordTablePanelLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(recordTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        recordTablePanelLayout.setVerticalGroup(
            recordTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordTablePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(recorTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recordTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeRecordTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout recordTableDialogLayout = new javax.swing.GroupLayout(recordTableDialog.getContentPane());
        recordTableDialog.getContentPane().setLayout(recordTableDialogLayout);
        recordTableDialogLayout.setHorizontalGroup(
            recordTableDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recordTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        recordTableDialogLayout.setVerticalGroup(
            recordTableDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recordTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        nonRecordWinPanel.setBackground(new java.awt.Color(255, 204, 255));

        nonRecordWinLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        nonRecordWinLabel1.setForeground(new java.awt.Color(255, 0, 0));
        nonRecordWinLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nonRecordWinLabel1.setText("Победа на вашей стороне");

        nonRecordWinLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        nonRecordWinLabel2.setForeground(new java.awt.Color(102, 102, 102));
        nonRecordWinLabel2.setText("К сожалению, Ваш результат не попал в топ 10");

        nonRecordEndButton.setBackground(new java.awt.Color(153, 153, 255));
        nonRecordEndButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        nonRecordEndButton.setForeground(new java.awt.Color(51, 51, 51));
        nonRecordEndButton.setText("Закончить игру");
        nonRecordEndButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonRecordEndButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nonRecordWinPanelLayout = new javax.swing.GroupLayout(nonRecordWinPanel);
        nonRecordWinPanel.setLayout(nonRecordWinPanelLayout);
        nonRecordWinPanelLayout.setHorizontalGroup(
            nonRecordWinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nonRecordWinPanelLayout.createSequentialGroup()
                .addGroup(nonRecordWinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nonRecordWinPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(nonRecordWinLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nonRecordWinPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(nonRecordWinLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nonRecordWinPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(nonRecordEndButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        nonRecordWinPanelLayout.setVerticalGroup(
            nonRecordWinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nonRecordWinPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(nonRecordWinLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(nonRecordWinLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(nonRecordEndButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout nonRecordWinDialogLayout = new javax.swing.GroupLayout(nonRecordWinDialog.getContentPane());
        nonRecordWinDialog.getContentPane().setLayout(nonRecordWinDialogLayout);
        nonRecordWinDialogLayout.setHorizontalGroup(
            nonRecordWinDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nonRecordWinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        nonRecordWinDialogLayout.setVerticalGroup(
            nonRecordWinDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nonRecordWinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bagOfItemesPanel.setBackground(new java.awt.Color(190, 182, 135));

        bagOfItemsLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        bagOfItemsLabel.setForeground(new java.awt.Color(51, 51, 51));
        bagOfItemsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bagOfItemsLabel.setText("Мешок предметов");

        smallPotionRadio.setBackground(new java.awt.Color(190, 182, 135));
        smallPotionRadio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        smallPotionRadio.setForeground(new java.awt.Color(0, 0, 0));
        smallPotionRadio.setText("Малое зелье лечение, 0 шт");
        smallPotionRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallPotionRadioActionPerformed(evt);
            }
        });

        bigPotionRadio.setBackground(new java.awt.Color(190, 182, 135));
        bigPotionRadio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        bigPotionRadio.setForeground(new java.awt.Color(0, 0, 0));
        bigPotionRadio.setText("Большое зелье лечение, 0 шт");
        bigPotionRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigPotionRadioActionPerformed(evt);
            }
        });

        ressurectionCrossRadio.setBackground(new java.awt.Color(190, 182, 135));
        ressurectionCrossRadio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        ressurectionCrossRadio.setForeground(new java.awt.Color(0, 0, 0));
        ressurectionCrossRadio.setText("Крест возрождения, 0 шт");

        useItemButton.setBackground(new java.awt.Color(239, 237, 14));
        useItemButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        useItemButton.setForeground(new java.awt.Color(0, 0, 0));
        useItemButton.setText("Использовать");
        useItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bagOfItemesPanelLayout = new javax.swing.GroupLayout(bagOfItemesPanel);
        bagOfItemesPanel.setLayout(bagOfItemesPanelLayout);
        bagOfItemesPanelLayout.setHorizontalGroup(
            bagOfItemesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bagOfItemesPanelLayout.createSequentialGroup()
                .addGroup(bagOfItemesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bagOfItemesPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(bagOfItemesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bigPotionRadio)
                            .addComponent(ressurectionCrossRadio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(smallPotionRadio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bagOfItemsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bagOfItemesPanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(useItemButton)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        bagOfItemesPanelLayout.setVerticalGroup(
            bagOfItemesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bagOfItemesPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bagOfItemsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(smallPotionRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bigPotionRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ressurectionCrossRadio)
                .addGap(50, 50, 50)
                .addComponent(useItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bagOfItemsDialogLayout = new javax.swing.GroupLayout(bagOfItemsDialog.getContentPane());
        bagOfItemsDialog.getContentPane().setLayout(bagOfItemsDialogLayout);
        bagOfItemsDialogLayout.setHorizontalGroup(
            bagOfItemsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bagOfItemesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bagOfItemsDialogLayout.setVerticalGroup(
            bagOfItemsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bagOfItemesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cannotUsePanel.setBackground(new java.awt.Color(243, 120, 120));

        uCannotUseLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        uCannotUseLabel.setForeground(new java.awt.Color(51, 51, 51));
        uCannotUseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uCannotUseLabel.setText("Вы не можете использовать ");

        thisItemLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        thisItemLabel.setForeground(new java.awt.Color(51, 51, 51));
        thisItemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thisItemLabel.setText("этот предмет");

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(51, 51, 51));
        jButton11.setText("ОК");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cannotUsePanelLayout = new javax.swing.GroupLayout(cannotUsePanel);
        cannotUsePanel.setLayout(cannotUsePanelLayout);
        cannotUsePanelLayout.setHorizontalGroup(
            cannotUsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cannotUsePanelLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(cannotUsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cannotUsePanelLayout.createSequentialGroup()
                        .addComponent(uCannotUseLabel)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cannotUsePanelLayout.createSequentialGroup()
                        .addComponent(thisItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))))
            .addGroup(cannotUsePanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cannotUsePanelLayout.setVerticalGroup(
            cannotUsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cannotUsePanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(uCannotUseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thisItemLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout cannotUseDialogLayout = new javax.swing.GroupLayout(cannotUseDialog.getContentPane());
        cannotUseDialog.getContentPane().setLayout(cannotUseDialogLayout);
        cannotUseDialogLayout.setHorizontalGroup(
            cannotUseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cannotUsePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cannotUseDialogLayout.setVerticalGroup(
            cannotUseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cannotUsePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainMenuPanel.setBackground(new java.awt.Color(255, 255, 255));

        mortalKombatLabel.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        mortalKombatLabel.setForeground(new java.awt.Color(204, 204, 0));
        mortalKombatLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mortalKombatLabel.setText("Mortal Kombat");

        startNewGameButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        startNewGameButton.setText("Начать новую игру");
        startNewGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startNewGameButtonActionPerformed(evt);
            }
        });

        showResultTableButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        showResultTableButton.setText("Посмотреть таблицу \nрезультатов");
        showResultTableButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        showResultTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showResultTableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(showResultTableButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(startNewGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(mortalKombatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(mortalKombatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showResultTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startNewGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startNewGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startNewGameButtonActionPerformed
        fightFrame.setVisible(rootPaneCheckingEnabled);
        fightFrame.setSize(1000,700);
        
        player = game.NewHuman(playerHealthBar);
        
        enemy = game.NewEnemy(enemyIconLabel, enemyNameLAbel, enemyDamageLabel, enemyHealthLabel, enemyHealthBar);
        
        game.change.NewRoundTexts(player, enemy,
                pointsValueLabel, experienceValueLabel, playerLevelLabel, enemyLevelLabel, playerHealthLabel, enemyHealthLabel, playerDamageLabel,
                turnLabel, lastActionLabel, game.fight.i, items, smallPotionRadio, bigPotionRadio, ressurectionCrossRadio);
        
        /*game.action.setEnemyes();
        enemy = game.action.ChooseEnemy(jLabel4, jLabel5, jLabel10, jLabel13);
                //a.ChooseEmemy(player, jLabel4, jProgressBar2, jLabel5, jLabel10, jLabel13);
        
        //Fight f = new Fight();
        
        game.action.HP(player, jProgressBar1);
        game.action.HP(enemy, jProgressBar2);
        jProgressBar2.setMaximum(enemy.getMaxHealth());*/
        
    }//GEN-LAST:event_startNewGameButtonActionPerformed

    private void atackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atackButtonActionPerformed
        game.fight.Hit(player, enemy, 1, enemyHealthLabel, playerHealthLabel, youWinDialog,
                youWinLabel, game.action, playerHealthBar, enemyHealthBar, recordWinDialog, 
                nonRecordWinDialog, fightFrame, game.getResults(), recordWinLabel, nonRecordWinLabel1, 
                turnLabel, effectLabel, lastActionLabel, items, ressurectionCrossRadio);
        
    }//GEN-LAST:event_atackButtonActionPerformed

    private void defendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defendButtonActionPerformed
        game.fight.Hit(player, enemy, 0, enemyHealthLabel, playerHealthLabel, youWinDialog,
                youWinLabel, game.action, playerHealthBar, enemyHealthBar, recordWinDialog, 
                nonRecordWinDialog, fightFrame, game.getResults(), recordWinLabel, nonRecordWinLabel1, 
                turnLabel, effectLabel, lastActionLabel, items, ressurectionCrossRadio);
    }//GEN-LAST:event_defendButtonActionPerformed

    private void youWinContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_youWinContinueButtonActionPerformed

        enemy=game.fight.NewRound(player, enemyIconLabel, playerHealthBar, enemyHealthBar,
                enemyNameLAbel, enemyDamageLabel, enemyHealthLabel, game.action);

        
        game.change.NewRoundTexts(player, enemy,
                pointsValueLabel, experienceValueLabel, playerLevelLabel, enemyLevelLabel, playerHealthLabel, enemyHealthLabel, playerDamageLabel,
                turnLabel, lastActionLabel, game.fight.i, items, smallPotionRadio, bigPotionRadio, ressurectionCrossRadio);

        youWinDialog.dispose();
    }//GEN-LAST:event_youWinContinueButtonActionPerformed

    private void recordWinNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordWinNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recordWinNameFieldActionPerformed

    private void recordWinEndButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordWinEndButtonActionPerformed
        try {
            game.EndGameTop(player, recordWinNameField, recordTable);
        } catch (IOException ex) {
            Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
        }
        recordWinDialog.dispose();
        recordWinNameField.setText("");
    }//GEN-LAST:event_recordWinEndButtonActionPerformed

    private void closeRecordTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeRecordTableButtonActionPerformed
        recordTableDialog.dispose();
    }//GEN-LAST:event_closeRecordTableButtonActionPerformed

    private void showResultTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showResultTableButtonActionPerformed
        recordTableDialog.setVisible(true);
        recordTableDialog.setBounds(100, 100, 580, 450);
    }//GEN-LAST:event_showResultTableButtonActionPerformed

    private void nonRecordEndButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonRecordEndButtonActionPerformed
        nonRecordWinDialog.dispose();
    }//GEN-LAST:event_nonRecordEndButtonActionPerformed

    private void smallPotionRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallPotionRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallPotionRadioActionPerformed

    private void bigPotionRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigPotionRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigPotionRadioActionPerformed

    private void useItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useItemButtonActionPerformed
        if(smallPotionRadio.isSelected()){
            nameButton="jRadioButton1";
        }
        if(bigPotionRadio.isSelected()){
            nameButton="jRadioButton2";
        }
        if(ressurectionCrossRadio.isSelected()){
            nameButton="jRadioButton3";
        }
        game.action.UseItem(player, items, nameButton, cannotUseDialog, bagOfItemsDialog);
        game.action.HP(player, playerHealthBar);
        playerHealthLabel.setText(player.getHealth() + "/" + player.getMaxHealth());
        game.change.BagText(items, smallPotionRadio, bigPotionRadio, ressurectionCrossRadio);
    }//GEN-LAST:event_useItemButtonActionPerformed

    private void itemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsButtonActionPerformed
        bagOfItemsDialog.setVisible(true);
        bagOfItemsDialog.setBounds(300, 200, 430, 350);
    }//GEN-LAST:event_itemsButtonActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        cannotUseDialog.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FightPanel;
    private javax.swing.JButton atackButton;
    private javax.swing.JPanel bagOfItemesPanel;
    private javax.swing.JDialog bagOfItemsDialog;
    private javax.swing.JLabel bagOfItemsLabel;
    private javax.swing.JRadioButton bigPotionRadio;
    private javax.swing.JDialog cannotUseDialog;
    private javax.swing.JPanel cannotUsePanel;
    private javax.swing.JButton closeRecordTableButton;
    private javax.swing.JLabel damage1Label;
    private javax.swing.JLabel damage2Label;
    private javax.swing.JButton defendButton;
    private javax.swing.JLabel effectLabel;
    private javax.swing.JLabel enemyDamageLabel;
    private javax.swing.JProgressBar enemyHealthBar;
    private javax.swing.JLabel enemyHealthLabel;
    private javax.swing.JLabel enemyIconLabel;
    private javax.swing.JLabel enemyLevelLabel;
    private javax.swing.JLabel enemyNameLAbel;
    private javax.swing.JLabel experienceLabel;
    private javax.swing.JLabel experienceValueLabel;
    private javax.swing.JFrame fightFrame;
    private javax.swing.JLabel fightLabel;
    private javax.swing.ButtonGroup itemBagBurronGroup;
    private javax.swing.JButton itemsButton;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel lastActionLabel;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JLabel mortalKombatLabel;
    private javax.swing.JButton nonRecordEndButton;
    private javax.swing.JDialog nonRecordWinDialog;
    private javax.swing.JLabel nonRecordWinLabel1;
    private javax.swing.JLabel nonRecordWinLabel2;
    private javax.swing.JPanel nonRecordWinPanel;
    private javax.swing.JLabel playerDamageLabel;
    private javax.swing.JProgressBar playerHealthBar;
    private javax.swing.JLabel playerHealthLabel;
    private javax.swing.JLabel playerIconLabel;
    private javax.swing.JLabel playerLevelLabel;
    private javax.swing.JLabel playerNameLabel;
    private javax.swing.JLabel pointLabel;
    private javax.swing.JLabel pointsValueLabel;
    private javax.swing.JLabel recorTableLabel;
    private javax.swing.JTable recordTable;
    private javax.swing.JDialog recordTableDialog;
    private javax.swing.JPanel recordTablePanel;
    private javax.swing.JScrollPane recordTableScroll;
    private javax.swing.JDialog recordWinDialog;
    private javax.swing.JButton recordWinEndButton;
    private javax.swing.JLabel recordWinLabel;
    private javax.swing.JLabel recordWinLabel1;
    private javax.swing.JLabel recordWinLabel2;
    private javax.swing.JTextField recordWinNameField;
    private javax.swing.JPanel recordWinPanel;
    private javax.swing.JRadioButton ressurectionCrossRadio;
    private javax.swing.JButton showResultTableButton;
    private javax.swing.JRadioButton smallPotionRadio;
    private javax.swing.JButton startNewGameButton;
    private javax.swing.JLabel thisItemLabel;
    private javax.swing.JLabel turnLabel;
    private javax.swing.JLabel uCannotUseLabel;
    private javax.swing.JButton useItemButton;
    private javax.swing.JButton youWinContinueButton;
    private javax.swing.JDialog youWinDialog;
    private javax.swing.JLabel youWinLabel;
    private javax.swing.JPanel youWinPanel;
    // End of variables declaration//GEN-END:variables
}
